[window]
padding = { x = 4, y = 4 }
startup_mode = "Maximized"

[font]
normal = { family = "AdwaitaMono Nerd Font" }
size = 12

[cursor]
thickness = 0.2

[terminal]
shell = { program = "wsl", args = ["-d", "ubuntu", "--cd", "~"] }

[general]
import = [ "themes/mellow.toml" ]

[colors.primary]
background = '#000000'

[colors.normal]
blue = '#54546D'
